### PR TITLE
Dev/controller

### PR DESCRIPTION
**Pull request by rwpr**
This is the new feature called controller. What's inside this file is...

### CODE REVIEW

**Comment by rwpr** [comment]
@josh1812 @enghong82 @bestofthesoul review these codes!

**Comment by hollowaykeanho** [comment]
I'm okay with her code.

**Comment by enghong82** [comment]
looking good....

**Comment by rwpr** [comment]
are you alright with this code, @bestofthesoul ?

**Comment by bestofthesoul** [comment]
blabla

**Comment by josh1812** [comment]
so bad, change it all

**Comment by hollowaykeanho** [comment]
Ask to add cars file

**Comment by rwpr** [comment]
i've added car file

**Pull request merged**
